Lmod has detected the following error: The following module(s) are unknown:
"Anaconda3/2022.05"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "Anaconda3/2022.05"

Also make sure that all modulefiles written in TCL start with the string
#%Module



/var/spool/slurm/slurmd/job7878358/slurm_script: line 19: activate: No such file or directory
Running simple training
----IPC----
Running simple training
Total number of trials: 3200
Trial 1/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=1, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.0
Trial 2/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=1, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.1
Trial 3/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=1, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.2
Trial 4/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=1, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.3
Trial 5/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=1, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.4
Trial 6/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.1, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.5
Trial 7/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.1, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.6
Trial 8/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.1, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.7
Trial 9/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.1, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.8
Trial 10/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.1, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.9
Trial 11/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.01, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.10
Trial 12/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.01, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.11
Trial 13/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.01, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.12
Trial 14/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.01, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.13
Trial 15/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.01, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.14
Trial 16/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.001, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.15
Trial 17/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.001, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.16
Trial 18/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.001, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.17
Trial 19/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.001, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.18
Trial 20/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.001, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.19
Trial 21/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.0001, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.20
Trial 22/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.0001, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.21
Trial 23/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.0001, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.22
Trial 24/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.0001, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.23
Trial 25/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.0001, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.24
Trial 26/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=1, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.25
Trial 27/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=1, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.26
Trial 28/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=1, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.27
Trial 29/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=1, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.28
Trial 30/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=1, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.29
Trial 31/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.1, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.30
Trial 32/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.1, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.31
Trial 33/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.1, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.32
Trial 34/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.1, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.33
Trial 35/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.1, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878358.34
Trial 36/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.01, lr_weight=0.01
slurmstepd: error: *** JOB 7878358 ON gcn141 CANCELLED AT 2024-09-18T20:13:06 ***
slurmstepd: error: *** STEP 7878358.35 ON gcn141 CANCELLED AT 2024-09-18T20:13:06 ***

JOB STATISTICS
==============
Job ID: 7878358
Cluster: snellius
User/Group: etatar/etatar
State: CANCELLED (exit code 0)
Nodes: 1
Cores per node: 32
CPU Utilized: 00:00:02
CPU Efficiency: 0.09% of 00:35:12 core-walltime
Job Wall-clock time: 00:01:06
Memory Utilized: 4.88 MB
Memory Efficiency: 0.00% of 180.00 GB
