Lmod has detected the following error: The following module(s) are unknown:
"Anaconda3/2022.05"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "Anaconda3/2022.05"

Also make sure that all modulefiles written in TCL start with the string
#%Module



/var/spool/slurm/slurmd/job7878376/slurm_script: line 19: activate: No such file or directory
Running simple training
----IPC----
Running simple training
Total number of trials: 3200
Trial 1/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=1, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.0
Trial 2/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=1, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.1
Trial 3/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=1, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.2
Trial 4/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=1, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.3
Trial 5/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=1, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.4
Trial 6/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.1, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.5
Trial 7/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.1, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.6
Trial 8/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.1, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.7
Trial 9/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.1, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.8
Trial 10/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.1, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.9
Trial 11/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.01, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.10
Trial 12/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.01, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.11
Trial 13/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.01, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.12
Trial 14/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.01, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.13
Trial 15/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.01, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.14
Trial 16/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.001, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.15
Trial 17/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.001, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.16
Trial 18/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.001, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.17
Trial 19/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.001, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.18
Trial 20/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.001, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.19
Trial 21/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.0001, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.20
Trial 22/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.0001, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.21
Trial 23/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.0001, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.22
Trial 24/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.0001, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.23
Trial 25/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.01, lr_val=0.0001, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.24
Trial 26/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=1, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.25
Trial 27/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=1, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.26
Trial 28/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=1, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.27
Trial 29/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=1, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.28
Trial 30/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=1, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.29
Trial 31/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.1, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.30
Trial 32/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.1, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.31
Trial 33/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.1, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.32
Trial 34/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.1, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.33
Trial 35/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.1, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.34
Trial 36/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.01, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.35
Trial 37/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.01, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.36
Trial 38/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.01, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.37
Trial 39/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.01, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.38
Trial 40/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.01, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.39
Trial 41/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.001, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.40
Trial 42/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.001, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.41
Trial 43/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.001, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.42
Trial 44/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.001, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.43
Trial 45/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.001, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.44
Trial 46/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.0001, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.45
Trial 47/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.0001, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.46
Trial 48/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.0001, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.47
Trial 49/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.0001, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.48
Trial 50/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=0.001, lr_val=0.0001, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.49
Trial 51/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=uniform, lr_val=1, lr_weight=0.01
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.50
Trial 52/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=uniform, lr_val=1, lr_weight=0.001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.51
Trial 53/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=uniform, lr_val=1, lr_weight=0.0001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.52
Trial 54/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=uniform, lr_val=1, lr_weight=0.00001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.53
Trial 55/3200: Running with graph_type=fully_connected, batch_size=1, T=1, weight_init=uniform, lr_val=1, lr_weight=0.000001
Traceback (most recent call last):
  File "/gpfs/home4/etatar/GraphPredCod2/scr/train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
srun: error: gcn141: task 0: Exited with exit code 1
srun: Terminating StepId=7878376.54
slurmstepd: error: *** JOB 7878376 ON gcn141 CANCELLED AT 2024-09-18T20:16:02 ***

JOB STATISTICS
==============
Job ID: 7878376
Cluster: snellius
User/Group: etatar/etatar
State: CANCELLED (exit code 0)
Nodes: 1
Cores per node: 32
CPU Utilized: 00:00:03
CPU Efficiency: 0.12% of 00:42:08 core-walltime
Job Wall-clock time: 00:01:19
Memory Utilized: 4.76 MB
Memory Efficiency: 0.00% of 180.00 GB
